apiVersion: v2
name: smart-redact
description: A Helm chart for deploying Smart Redact - PII detection and redaction service by PDF Tools AG
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - pii
  - redaction
  - pdf
  - smart-redact
home: https://www.pdf-tools.com
sources:
  - https://github.com/pdf-tools/smart-redact-samples
maintainers:
  - name: PDF Tools AG
