apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-redact-config
  namespace: smart-redact
data:
  # Shared
  FILE_STORAGE_TYPE: "HostFileSystem"
  FILE_STORAGE_PATH: "/app/storage_folder"
  DEK_TTL_MINUTES: "1440"

  # Manager
  MANAGER_DB_TYPE: "PostgreSql"
  MANAGER_WORKER_URL: "http://smart-redact-worker:4885/"

  # Orchestrator
  ORCHESTRATOR_DB_TYPE: "PostgreSql"
  ORCHESTRATOR_MANAGER_URL: "http://smart-redact-manager:9982/"
  ORCHESTRATOR_POLLING_INTERVAL: "3"
